---
start_date: 2017-07-01 00:00:00
end_date: 2017-09-01 00:00:00
frequency: "12H"
seasonality:
  - "daily"
trend:
  linear: [3, 1]
data_type: "Additive"
noise:
  percentage: 0.1
outlier:
  percentage: 0.1
missing:
  percentage: 0.05
datasets_number: 10
