version: "1.0"
services:
# Postgres service
  db:
    image: postgres
    container_name: time-series-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=time-series
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=r87hty5
    ports:
      -  5433:5432
    networks:
      - simulator-network
# Apache NiFi Service
  apache-nifi-simulator:
    image: apache/nifi:latest
    container_name: time-series-nifi
    volumes:
      - ./drivers:/opt/nifi/nifi-current/drivers
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_db:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    ports:
      - 8443:8443
      - 5000:5000
    networks:
      - simulator-network
# Simulator service
  sim-api:
    image: simulator:1.0
    container_name: time-series-gen
    command: >
      bash -c " python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - generated-datasets:/simulator/generated_datasets
      - migrations:/simulator/simulator_api/migrations
      - consumer-data:/simulator/consumer_data
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=time-series
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=r87hty5
    depends_on:
      - db
    networks:
      - simulator-network
# Kafka Confluent Service
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
          - simulator-network
  kafka-broker:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data-producer:/kafka-data
    networks:
      - simulator-network
    depends_on:
      - sim-api
      - zookeeper

volumes:
  generated-datasets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./generated_datasets
  consumer-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./consumer_data
  migrations:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./simulator_api/migrations
  nifi_state:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nifi/nifi_state
  nifi_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nifi/nifi_db
  nifi_flowfile:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nifi/nifi_flowfile
  nifi_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nifi/nifi_content
  nifi_provenance:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nifi/nifi_provenance
  kafka-data-producer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./time_series_data_producer/producer
#  kafka-data-consumer:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./time_series_data_producer/producer

networks:
  simulator-network:
    driver: bridge
