# Generated by Django 4.1 on 2023-09-18 06:55

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simulator_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=5)),
                ('trend_coefficients', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('missing_percentage', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('outlier_percentage', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('noise_level', models.IntegerField()),
                ('cycle_amplitude', models.IntegerField()),
                ('cycle_frequency', models.IntegerField()),
                ('producing_status', models.CharField(max_length=5, validators=[simulator_api.models.validate_producing_status])),
            ],
        ),
        migrations.CreateModel(
            name='SimulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(default='additive', max_length=14, validators=[simulator_api.models.validate_time_series_type])),
                ('use_case_name', models.CharField(max_length=20)),
                ('meta_data', models.CharField(max_length=200)),
                ('producer_type', models.CharField(max_length=9, validators=[simulator_api.models.validate_producer_type])),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=7, validators=[simulator_api.models.validate_seasonality_type])),
                ('multiplier', models.IntegerField()),
                ('phase_shift', models.IntegerField()),
                ('amplitude', models.IntegerField()),
                ('dataset_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.datasetconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='datasetconfiguration',
            name='simulation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulationdata'),
        ),
    ]
