# Generated by Django 4.1.11 on 2023-10-01 18:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=5)),
                ('trend_coefficients', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None)),
                ('missing_percentage', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('outlier_percentage', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('noise_level', models.IntegerField()),
                ('cycle_amplitude', models.IntegerField()),
                ('cycle_frequency', models.IntegerField()),
                ('producing_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], default='Submitted', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_dataset', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('ADDITIVE', 'Additive'), ('MULTIPLICATIVE', 'Multiplicative')], default='ADDITIVE', max_length=14)),
                ('use_case_name', models.CharField(max_length=50, unique=True)),
                ('meta_data', models.CharField(default='', max_length=200)),
                ('producer_type', models.CharField(choices=[('csv', 'csv'), ('kafka', 'Kafka')], default='csv', max_length=9)),
                ('process_id', models.BigIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=7)),
                ('multiplier', models.IntegerField()),
                ('phase_shift', models.IntegerField()),
                ('amplitude', models.IntegerField()),
                ('dataset_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_components', to='simulator_api.datasetconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='datasetconfiguration',
            name='simulation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='simulator_api.simulationdata'),
        ),
    ]
