# Generated by Django 4.1 on 2023-09-18 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetconfiguration',
            name='trend_coefficients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None),
        ),
    ]
