# Generated by Django 4.1 on 2023-09-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0002_alter_datasetconfiguration_trend_coefficients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetconfiguration',
            name='simulation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='simulator_api.simulationdata'),
        ),
        migrations.AlterField(
            model_name='seasonalitymodel',
            name='dataset_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_components', to='simulator_api.datasetconfiguration'),
        ),
    ]
