# Generated by Django 4.1 on 2023-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0004_alter_datasetconfiguration_producing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationdata',
            name='use_case_name',
            field=models.CharField(default='UC-<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
