# Generated by Django 4.1 on 2023-09-18 15:02

from django.db import migrations, models
import simulator_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0005_alter_simulationdata_use_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetconfiguration',
            name='producing_status',
            field=models.CharField(default='Submitted', max_length=14, validators=[simulator_api.models.validate_producing_status]),
        ),
    ]
