# Generated by Django 4.1 on 2023-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0007_alter_simulationdata_use_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationdata',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
