# Generated by Django 4.1 on 2023-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0008_alter_simulationdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationdata',
            name='name',
        ),
        migrations.AddField(
            model_name='simulationdata',
            name='process_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='simulationdata',
            name='use_case_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
